# Generated by Django 4.2.7 on 2023-12-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='prieM',
            new_name='priceM',
        ),
    ]
