# Generated by Django 4.2.7 on 2023-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_priem_pizza_pricem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='priceL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='priceM',
            field=models.IntegerField(),
        ),
    ]
