# Generated by Django 4.2.7 on 2023-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_pizza_pricel_alter_pizza_pricem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.IntegerField()),
                ('priceL', models.IntegerField()),
                ('bImage', models.URLField()),
            ],
        ),
    ]
